# docker-composeのversion 基本3
version: '3'

# Host側にdb保存場所(db-data)を作成する
# ・他のコンテナとdbを共有する場合
# ・コンテナを消したらdbも消える。その為コンテナの外にdb保存ファイルを作成する
volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # 相対パスを指定
      - ".:/pra"
    # コンテナ内で使用する環境変数を指定
    environment:
      # database.ymlで使用
      - "DATABASE_PASSWORD=postgres"
    # tty = -itのtのこと
    tty: true
    # stdin_open = -itのiのこと
    stdin_open: true
    # depends_onを記述したサービスより、depends_onで指定したサービスを先に作成する
    # 今回だとdbを作成した後にwebを作成する
    depends_on:
      - db
    # webからdbにアクセスするため
    links:
      - db

  db:
    # dockerhubからpostgresのイメージを取ってくる
    image: postgres
    # postgresのデータを保存する場所
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'