# CircleCIのバージョン
version: 2
  # 1つ以上のjobを設定する
  jobs:
    # jobが1つだけの場合、job名はbuildでなければならない
    build:
      # docker/machine/macos のいずれかをconfig.ymlに記載する必要がある
      docker:
        # ベースとなるDockerイメージを指定
        - image: circleci/ruby:2.4.1
      steps:
        - checkout
        - run: echo "A first hello"