version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3
    working_directory: ~/pra
    steps:
      - checkout
      - run:
          name: Run test
          command: 'ruby test_sum.rb'

workflows:
  version: 2
  workflows:
    jobs:
      - test
    # run tests!
    - run:
        name: Run rspec
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
            circleci tests split --split-by=timings)"
          bundle exec rspec